version: 0.1
phases:
  install:
    commands:
      - mkdir setup
      - pip install -r sparrow/requirements.txt -t ./setup
      - cp sparrow/creds.json setup/creds.json
      - cp sparrow/sparrow_nokms.py setup/sparrow_nokms.py
      - cp deployment/samTemplate.yaml setup/samTemplate.yaml
      - aws cloudformation package --template-file deployment/samTemplate.yaml --s3-bucket csgawslambdatest --output-template-file setup/outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
  base-directory: 'setup'